name: vietnamcovidtracking
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: 8.0.0
  equatable:  ^2.0.3
  http: ^0.13.0
  line_icons: ^2.0.1
  flutter_snake_navigationbar: ^0.5.0  
  salomon_bottom_bar: ^3.2.0
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  syncfusion_flutter_maps: ^19.4.40-beta
  syncfusion_flutter_charts: ^19.4.38
  flutter_spinkit: ^5.1.0
  tiengviet: ^0.5.0
  webfeed: ^0.7.0
  carousel_slider: ^4.0.0
  cached_network_image: 3.1.0+1
  flutter_webview_plugin: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    # - assets/icons/
    - assets/svg/
    - assets/fonts/BeFonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
      - family: BeFonts
        fonts:    
          - asset: assets/fonts/BeFonts/BeVietnam-Thin.ttf
            weight: 100         
          - asset: assets/fonts/BeFonts/BeVietnam-ThinItalic.ttf
            weight: 100
            style: italic
          - asset: assets/fonts/BeFonts/BeVietnam-Light.ttf
            weight: 200         
          - asset: assets/fonts/BeFonts/BeVietnam-LightItalic.ttf
            weight: 200
            style: italic
          - asset: assets/fonts/BeFonts/BeVietnam-Regular.ttf
            weight: 300         
          - asset: assets/fonts/BeFonts/BeVietnam-Medium.ttf
            weight: 400         
          - asset: assets/fonts/BeFonts/BeVietnam-MediumItalic.ttf
            weight: 400
            style: italic
          - asset: assets/fonts/BeFonts/BeVietnam-SemiBold.ttf
            weight: 500         
          - asset: assets/fonts/BeFonts/BeVietnam-SemiBoldItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/BeFonts/BeVietnam-Bold.ttf
            weight: 600         
          - asset: assets/fonts/BeFonts/BeVietnam-BoldItalic.ttf
            weight: 600    
            style: italic
          - asset: assets/fonts/BeFonts/BeVietnam-ExtraBold.ttf
            weight: 700         
          - asset: assets/fonts/BeFonts/BeVietnam-ExtraBoldItalic.ttf
            weight: 700    
            style: italic       
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
